#this will dump facts for each host into a separate file and put to S3 bucket

- hosts: linux-servers

  tasks:
  - name: Fetch the ec2_facts for the server
    action: ec2_facts

  - name: dump facts to file
    local_action: copy content='{{ hostvars[inventory_hostname] | to_nice_json}}' dest="/tmp/{{ ansible_ec2_instance_id }}.json"

  - name: remove not neccesary fields
    local_action: lineinfile dest=/tmp/{{ ansible_ec2_instance_id }}.json regexp='ec2_network_interfaces_macs' state=absent

  - name: replace some fields
    local_action: replace dest=/tmp/{{ ansible_ec2_instance_id }}.json regexp='^(.*)ansible_ec2(.*)$' replace='\1ec2\2'

  - name: remove password from files
    local_action: lineinfile dest=/tmp/{{ ansible_ec2_instance_id }}.json regexp='ansible_ssh_pass' state=absent

  - name: upload facts into s3
    local_action: s3 bucket=ops-ansible object=/ansiblefacts/{{ ansible_ec2_instance_id }}.json src="/tmp/{{ ansible_ec2_instance_id }}.json" mode=put overwrite=True
